### ISSUE TITLE
npm is crashing when trying to resume the upload

### ISSUE THREAD

**Issue by codex-corp** [kukhariev/node-uploadx#3]
**I'm opening this issue because:**
 npm is crashing.

> Error: EPERM: operation not permitted, open 'F:\server\universal\public\bbb_sunflower_2160p_30fps_normal.mp4'

**supporting information**:
npm -v prints: 6.1.0
node -v prints: 8.11.3
Windows, OS X/macOS, or Linux?: Windows 10
Network issues: no

@kukhariev thanks for your efforts!

**Comment by kukhariev** [comment]
Can you provide a stack trace?

**Comment by codex-corp** [comment]
@kukhariev 
Error: EPERM: operation not permitted, open 'F:\server\universal\public\bbb_sunflower_2160p_30fps_normal.mp4'
POST /upload?uploadType=uploadx 200 1.025 ms - 2
POST /upload?uploadType=uploadx 200 1.025 ms - 2
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.

**Comment by kukhariev** [comment]
POST /upload?uploadType=uploadx **200** 1.025 ms - 2
status 200: middleware bypassed
missing 'x-upload-content-type'  header?
