### ISSUE TITLE
How to run functions and change response data

### ISSUE THREAD

**Issue by kontrollanten** [kukhariev/node-uploadx#318]
Thanks for this interesting module. I'm interested in using it for [Peertube](https://github.com/Chocobozzz/PeerTube) and we'd like to create a video entity upon file upload and then return id, etc to the client. According to the source code and examples it looks like it's not possible to modify the server response? A workaround could be to run an additional request after the upload is finished, but that may result in "orphaned" files (if the additional request fails) and will also not be as efficient.

**Comment by kukhariev** [comment]
You can use the `onComplete` option to inject id.
See  [examples/express-gcs.ts](https://github.com/kukhariev/node-uploadx/blob/8c9abd834c478c4a65bc65a3bebdacb38a052eff/examples/express-gcs.ts) and [examples/express.ts](https://github.com/kukhariev/node-uploadx/blob/8c9abd834c478c4a65bc65a3bebdacb38a052eff/examples/express.ts)

**Comment by kontrollanten** [comment]
Thanks for your quick reply! That's what I was looking for.

Another question: if we upload multiple files, is it possible to couple those files on the server side? The use case is that we want to upload an image and audio file and then "merge" those two on the server side. This is done before we have any id, so we can't send that from the client.

**Comment by kontrollanten** [comment]
Sorry for spamming with questions. I've another question. Is it possible to read the `request` object in `onComplete`? We've an auth middleware that adds a user object which we need to read upon upload.

I saw that there's [an example](https://github.com/kukhariev/node-uploadx/blob/8c9abd834c478c4a65bc65a3bebdacb38a052eff/examples/express.ts#L8-L11) with auth middleware, but I couldn't see that the data is used in `onComplete`?

**Comment by kukhariev** [comment]
Here's a simple example of how you can use metadata:

```ts
app.use(auth);

const combineMap = new Map<string, string>();

const onComplete: OnComplete<DiskFile> = async file => {
  const dstpath = `upload/${file.name}`;
  if (typeof file.metadata['videoDest'] === 'string') {
    const videoDest = `video/${file.userId || ''}-${file.metadata['videoDest']}`;
    const combine = combineMap.get(videoDest);
    combineMap.set(videoDest, dstpath);
    if (combine) {
      console.log('ffmpeg', ['-i', dstpath, '-i', combine, '-c:a', 'copy', videoDest]);
      combineMap.delete(videoDest);
    }
  }
};

```

The client must set the same `videoDest` metadata for image and audio files.

**Comment by kontrollanten** [comment]
Thanks for the example. In our case the user data is stored in `res.locals`. Would it be possible to rewrite node-uploadx so it calls `next()` instead of using the `onComplete` cb? Then it could be used as a regular mw.

**Comment by kukhariev** [comment]
Legacy  [node-uploadx@2.*](https://github.com/kukhariev/node-uploadx/tree/v2.0.2)  versions  supported this.

It will take some time to look into restoring this feature.

**Comment by kontrollanten** [comment]
> Legacy [node-uploadx@2.*](https://github.com/kukhariev/node-uploadx/tree/v2.0.2) versions supported this.
> 
> It will take some time to look into restoring this feature.

Thanks. I was just started to try to implement it. Was it any problems with that solution or why did you leave it?

**Comment by kukhariev** [comment]
I don't remember for sure, maybe compatibility with fastify .
