### ISSUE TITLE
Limit chunk upload

### ISSUE THREAD

**Issue by Chocobozzz** [kukhariev/node-uploadx#335]
Hello,

Using uploadx protocol we can create a file with a specific size, but the disk storage does not check the chunk size is lower or equal to the file size. So an uploader can upload as much data it wants.

I think we should add a check in the `put` handler: https://github.com/kukhariev/node-uploadx/blob/02883fc7d65dc2d0eb2c109168ce79caa8dd0677/packages/core/src/handlers/uploadx.ts#L51-L54

**Comment by rigelk** [comment]
@kukhariev thanks a bunch for your taking care of the issue resolution so fast!
