### ISSUE TITLE
Client for React

### ISSUE THREAD

**Issue by jienco** [kukhariev/node-uploadx#373]
Hi, I have a project where I use `ngx-uploadx` in the client with Angular, combined with a node server using `node-uploadx`.

I am migrating the client project to React. Is there any `ngx-uploadx` alternative that is compatible with React?

I want to keep `node-uploadx` in the server side.

Thank you very much in advance.

**Comment by kukhariev** [comment]
Hi, `node-uploadx` supports [tus](examples/express-tus.ts) API  and it is potentially possible to use some react libs, e.g. [use-tus](https://github.com/kqito/use-tus).

**Comment by jienco** [comment]
Thank you very much @kukhariev I will try that
