### ISSUE TITLE
How i handle a upload progress and resume events?

### ISSUE THREAD

**Issue by maulikpatel1994** [kukhariev/node-uploadx#4]
please guide me in detail for proper demo how i use in my project.
i am using ngx-uploadx at angular side and i installed node-uploadx but i don't know completely how its works and manage resumable uploads even after i looged out and login after some time.

**Comment by kukhariev** [comment]
node-uploadx creates an MD5 hash (upload_id) from the POST payload and user ID from the auth middleware and sends it back to the client in the response location header and will be used to upload file chunks.
If the file uploading  is interrupted for any reason, just start upload the file again ((even on another computer,  the generated upload_id will remain the same)) ,node-uploadx will validate the file with this upload_id and force the client to start uploading only the missing parts of the file.

and no any event emits
```js
app.use(
  '/upload/',
  uploadx({
    maxUploadSize: '4GiB',
    allowMIME: ['video/*'],
    destination: req => `${VIDEOS}/${req.user.channel}/${req.body.name}`
  }),
  (req, res, next) => {
    if (req.file) {      //  <----- on completed  
      startProcess(req.file);
      res.json(req.file.metadata);
    } else {
      res.json();
    }
  }
);
```

**Comment by maulikpatel1994** [comment]
i want to upload a files in chunk to third party storage like amazon S3. so how can i manage a upload_id for  different users?

**Comment by kukhariev** [comment]
for s3 support, we need to create a composite adapter or enable s3 support in future versions of nginx-upload. low priority  :(
