### ISSUE TITLE
NODE-UPLOADX + .HTACCESS configuration. 

### ISSUE THREAD

**Issue by NadirBelhadj** [kukhariev/node-uploadx#467]
Hello there,

I am facing a problem when working with this package node-uploadx.

I installed node-uploadx normally on my local machine, I tested it by uploading a file, and it works perfectly on localhost, I found the file in  this url:
localhost:3000/upload/files

But when I deployed the project on CLOUDWAYS, the package didn't worked properly,  because When I tried to upload a file the file is uploading to this url :

https://127.0.0.1:3000 (this url is found and resolved from .htaccess configuration file)

while the file should be uploaded to another url (my  server url on cloudways, api.thebravespirit.org)

is there any suggestions about this problem?@kukhariev @onkeloki 

Thank you

**Comment by kukhariev** [comment]
Hello,
The `x-forwarded-host` or `host` headers are used to set the correct url.   Or you can set `useRelativeLocation` :

```ts
const options = {
  useRelativeLocation: true,
  ...
};
```

**Comment by NadirBelhadj** [comment]
Problem solved. Thank you
