### ISSUE TITLE
Are checksum used to verify upload?

### ISSUE THREAD

**Issue by kontrollanten** [kukhariev/node-uploadx#518]
I'm using PeerTube and we've had a lot of problems with corrupt video files and now I'm trying to investigate where the corruption happens. One possibility is that it happens during upload (which is done with node-uploadx). We're uploading pretty big files, 6-9 gb. Is there any checksum created on the client and sent to the server to verify that the file is in good condition when the upload is done?

**Comment by kukhariev** [comment]
There is no built-in checksum support yet.

**Comment by kontrollanten** [comment]
It seems that https://github.com/satazor/js-spark-md5 is fast and small for the client side. I've searched around for finding best practices about file upload checksums, but it was hard to find that much. A simple way would be:

1. A md5 checksum is calculated and sent with the initial POST
2. When the upload is done the server will verify the checksum and return accurate response

The drawback is that if the file is corrupt the user has to upload the file again. Then it would be better to check the integrity of each chunk and reupload the cunk if it's corrupt, but then we won't ensure that the complete file isn't harmed. Should we do a checksum verification for each chunk + the complete file?

**Comment by kukhariev** [comment]
For the whole file it is faster to calculate the checksum in parallel with the upload and compare it with the one given by the server in the response body or[  Digest header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Digest)

```ts
    if (state?.status === 'added') {
      calculateMd5(state.file).then((md5: string) => {
        state['md5'] = md5;
      });
    }
    if (state?.status === 'complete') {
      if (state['md5'] !== state.response?.md5) {
        throw new Error('md5 not match');
      }
    }
```
