### ISSUE TITLE
S3 direct upload: custom cache/etag storage

### ISSUE THREAD

**Issue by kontrollanten** [kukhariev/node-uploadx#645]
Would it be possible to provide an API to store file parts (etags and parts number) in a custom cache for s3 direct uploads? That would make it possible to keep the server stateless.

**Comment by kukhariev** [comment]
https://gist.github.com/kukhariev/7697ee79c69b1f8dfcf74002157882f5#complete-multipart-upload
but `"Parts"` are [optional ](https://github.com/kukhariev/node-uploadx/blob/1faa90bf30f14e018a632f471ff034a338d1a32c/packages/s3/src/s3-storage.ts#L265-L267)and you can actually send a simple `PATCH` request without a body to complete upload

```http
PATCH /files?upload_id=f8048cee0976d141-60a53b68e983de7e-9aa649a809275708 HTTP/1.1

Authorization: Bearer dXNlcjpwYXNz
Content-Type: application/json; charset=UTF-8
Host: example.com
Origin: http://example.com

{}
```

**Comment by kukhariev** [comment]
no, the server does not store etags .  The parts list is received from the client or from S3 `ListPartsCommand`
https://github.com/kukhariev/node-uploadx/blob/1faa90bf30f14e018a632f471ff034a338d1a32c/packages/s3/src/s3-storage.ts#L307-L309
