### ISSUE TITLE
@uploadx/s3 | how to change or add endpoint of digitalocean spaces

### ISSUE THREAD

**Issue by Aviico2** [kukhariev/node-uploadx#668]
Below I mention the example code: 

const { uploadx } = require("@uploadx/core");
const { S3Storage } = require('@uploadx/s3');

const storage = new S3Storage({
    endpoint: process.env.ENDPOINT // I want to add digitalocean endpoint here eg. https://{region}.digitaloceanspaces.com
    bucket: process.env.BACKET,
    region: process.env.REGION,
    apiVersion: '2006-03-01',
    credentials: {
        accessKeyId: process.env.ACCESS_KEY_ID,
        secretAccessKey: process.env.SECRET_ACCESS_KEY,
    },
    forcePathStyle: true,
    expiration: { maxAge: '1h', purgeInterval: '15min' },
    onComplete: file => {
        return 'completed'
    },
    filename: (file) => file.originalName
});

app.use('/uploads', uploadx({ storage }), function (req, res) {
    var file = req.body;
    res.send(file)
});

**_Error throw:_** 

Error: getaddrinfo ENOTFOUND testing.s3.nyc1amazonaws.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'testing.s3.nyc1.amazonaws.com',
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}

**Comment by kukhariev** [comment]
Hello.
 I can't test Spaces right now, but according to [this link](https://docs.digitalocean.com/products/spaces/reference/s3-sdk-examples/#setup-and-configuration), you need to set `forcePathStyle: false`

**Comment by Aviico2** [comment]
I tried with `forcePathStyle: false` but it also did not work same error was thrown.

**Comment by kukhariev** [comment]
It is possible that the `process.env.ENDPOINT` value is set incorrectly.
add `loglevel: 'debug'` to the configuration and look at the endpoint log value, it should be `https://nyc1.digitaloceanspaces.com`.

**Comment by Aviico2** [comment]
Log after adding `logLevel: 'debug'`:

`2023-10-25T17:08:09.515Z DEBUG uploadx: S3Storage config: {
  endpoint: 'https://xxxx.digitaloceanspaces.com',
  bucket: 'xxx',
  region: 'xxxx',
  apiVersion: '2006-03-01',
  credentials: {
    accessKeyId: 'xxx',
    secretAccessKey: 'xxx'
  },
  logLevel: 'debug',
  forcePathStyle: false,
  expiration: { maxAge: '1h', purgeInterval: '15min' },
  onComplete: [Function: onComplete],
  filename: [Function: filename],
  logger: [class BasicLogger]
}`

Still some error: 
`Error: getaddrinfo ENOTFOUND xxx.s3.xxxx.amazonaws.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'xxx.s3.xxxx.amazonaws.com',
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}`

**Comment by kukhariev** [comment]
I can't reproduce this error with "amazonaws.com".
Requests go correctly to 'nyc3.digitaloceanspaces.com':

```ts
import * as express from 'express';
import { uploadx } from '@uploadx/core';
import { S3Storage } from '@uploadx/s3';
const app = express();

const storage = new S3Storage({
  endpoint: 'https://nyc3.digitaloceanspaces.com',
  forcePathStyle: false,
  region: 'eu-west',
  credentials: {
    accessKeyId: 'xxx',
    secretAccessKey: 'xxxx'
  },
  bucket: 'testing-uploadx',
  onComplete: file => console.log('File upload complete: ', file),
  logLevel: 'debug'
});

app.use('/files', uploadx({ storage }));

app.listen(3002);
```

**Comment by Aviico2** [comment]
Thanks for this response problem is solved. The problem is getting files from the bucket, not in @uploadx/s3. working fine now.
