### ISSUE TITLE
ensureFile fsMkdir exists error

### ISSUE THREAD

**Issue by leighton-carr** [kukhariev/node-uploadx#7]
node-uploadx (Windows) is throwing an error when trying to upload to an existing directory due to ensureFile (utils.js) function.  The fsMkdir and fsClose/fsOpen are in the same try/catch, and an existing directory is causing the fsMkdir to throw an error and therefore skip the file creation step.  The server error then comes in the async create (disk-storage.js) function at the getFileSize step due to no file being created from ensureFile.

**Comment by kukhariev** [comment]
Thanks for the report.
