### ISSUE TITLE
[Help wanted] Module 'node-uploadx/lib/core' has no exported member 'Range'

### ISSUE THREAD

**Issue by hieutran106** [kukhariev/node-uploadx#8]
Hi,
I am using node-uploadx in a typescript project. When I compile source code (*.ts) to javascript file (*.js), an error is from node-uploadx as follows:
**Module 'node-uploadx/lib/core' has no exported member 'Range'.**
Is this because '@internal' decoration in the source code **(core/interface.ts)**  and how can I fix this issue? 
```
/**
 * @internal
 */
export interface Range {
  total?: number;
  end?: number;
  start?: number;
  id: string;
}
```
Thank you in advance.

**Comment by kukhariev** [comment]
Hi @hieutran106, thanks.
This is a bug, this interface should not be hidden.

**Comment by hieutran106** [comment]
The bug is fixed. Thank you for your work. You did a great project.
